/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TableRouteImport } from './routes/table'
import { Route as StaffLoginRouteImport } from './routes/staff-login'
import { Route as StaffConsoleRouteImport } from './routes/staff-console'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ResetPinRouteImport } from './routes/reset-pin'
import { Route as ResellerRouteImport } from './routes/reseller'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PesaswapAppRouteImport } from './routes/pesaswapApp'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as PayRouteImport } from './routes/pay'
import { Route as MerchantRouteImport } from './routes/merchant'
import { Route as GetStartedRouteImport } from './routes/get-started'
import { Route as EnquireRouteImport } from './routes/enquire'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConverterRouteImport } from './routes/converter'
import { Route as BeneficiariesRouteImport } from './routes/beneficiaries'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as TableTableIdRouteImport } from './routes/table.$tableId'
import { Route as RetailStoreIdRouteImport } from './routes/retail.$storeId'
import { Route as QCodeRouteImport } from './routes/q.$code'
import { Route as MeTokenRouteImport } from './routes/me.$token'
import { Route as DashboardWhatsappRouteImport } from './routes/dashboard/whatsapp'
import { Route as DashboardTelegramRouteImport } from './routes/dashboard/telegram'
import { Route as DashboardTablesRouteImport } from './routes/dashboard/tables'
import { Route as DashboardStaffRouteImport } from './routes/dashboard/staff'
import { Route as DashboardSettlementRouteImport } from './routes/dashboard/settlement'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardServicesRouteImport } from './routes/dashboard/services'
import { Route as DashboardRewardsRouteImport } from './routes/dashboard/rewards'
import { Route as DashboardReviewsRouteImport } from './routes/dashboard/reviews'
import { Route as DashboardRetentionRouteImport } from './routes/dashboard/retention'
import { Route as DashboardRetailRouteImport } from './routes/dashboard/retail'
import { Route as DashboardReportsRouteImport } from './routes/dashboard/reports'
import { Route as DashboardReorderRouteImport } from './routes/dashboard/reorder'
import { Route as DashboardQrRouteImport } from './routes/dashboard/qr'
import { Route as DashboardPromosRouteImport } from './routes/dashboard/promos'
import { Route as DashboardPricingRouteImport } from './routes/dashboard/pricing'
import { Route as DashboardPaymentsRouteImport } from './routes/dashboard/payments'
import { Route as DashboardPaymentMethodsRouteImport } from './routes/dashboard/payment-methods'
import { Route as DashboardOrdersRouteImport } from './routes/dashboard/orders'
import { Route as DashboardMenuRouteImport } from './routes/dashboard/menu'
import { Route as DashboardKnowledgeRouteImport } from './routes/dashboard/knowledge'
import { Route as DashboardInvoicesRouteImport } from './routes/dashboard/invoices'
import { Route as DashboardInventoryRouteImport } from './routes/dashboard/inventory'
import { Route as DashboardInboxRouteImport } from './routes/dashboard/inbox'
import { Route as DashboardForecastRouteImport } from './routes/dashboard/forecast'
import { Route as DashboardFloorplanRouteImport } from './routes/dashboard/floorplan'
import { Route as DashboardEnquiriesRouteImport } from './routes/dashboard/enquiries'
import { Route as DashboardDepositsRouteImport } from './routes/dashboard/deposits'
import { Route as DashboardCopilotRouteImport } from './routes/dashboard/copilot'
import { Route as DashboardContactsRouteImport } from './routes/dashboard/contacts'
import { Route as DashboardBookingsRouteImport } from './routes/dashboard/bookings'
import { Route as DashboardAutomationsRouteImport } from './routes/dashboard/automations'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard/analytics'
import { Route as DashboardAccountingRouteImport } from './routes/dashboard/accounting'
import { Route as BookBusinessIdRouteImport } from './routes/book.$businessId'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminMerchantsRouteImport } from './routes/admin/merchants'
import { Route as AdminFeaturesRouteImport } from './routes/admin/features'
import { Route as AdminActivityRouteImport } from './routes/admin/activity'

const TableRoute = TableRouteImport.update({
  id: '/table',
  path: '/table',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffLoginRoute = StaffLoginRouteImport.update({
  id: '/staff-login',
  path: '/staff-login',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffConsoleRoute = StaffConsoleRouteImport.update({
  id: '/staff-console',
  path: '/staff-console',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPinRoute = ResetPinRouteImport.update({
  id: '/reset-pin',
  path: '/reset-pin',
  getParentRoute: () => rootRouteImport,
} as any)
const ResellerRoute = ResellerRouteImport.update({
  id: '/reseller',
  path: '/reseller',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PesaswapAppRoute = PesaswapAppRouteImport.update({
  id: '/pesaswapApp',
  path: '/pesaswapApp',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const PayRoute = PayRouteImport.update({
  id: '/pay',
  path: '/pay',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantRoute = MerchantRouteImport.update({
  id: '/merchant',
  path: '/merchant',
  getParentRoute: () => rootRouteImport,
} as any)
const GetStartedRoute = GetStartedRouteImport.update({
  id: '/get-started',
  path: '/get-started',
  getParentRoute: () => rootRouteImport,
} as any)
const EnquireRoute = EnquireRouteImport.update({
  id: '/enquire',
  path: '/enquire',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConverterRoute = ConverterRouteImport.update({
  id: '/converter',
  path: '/converter',
  getParentRoute: () => rootRouteImport,
} as any)
const BeneficiariesRoute = BeneficiariesRouteImport.update({
  id: '/beneficiaries',
  path: '/beneficiaries',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TableTableIdRoute = TableTableIdRouteImport.update({
  id: '/$tableId',
  path: '/$tableId',
  getParentRoute: () => TableRoute,
} as any)
const RetailStoreIdRoute = RetailStoreIdRouteImport.update({
  id: '/retail/$storeId',
  path: '/retail/$storeId',
  getParentRoute: () => rootRouteImport,
} as any)
const QCodeRoute = QCodeRouteImport.update({
  id: '/q/$code',
  path: '/q/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const MeTokenRoute = MeTokenRouteImport.update({
  id: '/me/$token',
  path: '/me/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWhatsappRoute = DashboardWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTelegramRoute = DashboardTelegramRouteImport.update({
  id: '/telegram',
  path: '/telegram',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTablesRoute = DashboardTablesRouteImport.update({
  id: '/tables',
  path: '/tables',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStaffRoute = DashboardStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettlementRoute = DashboardSettlementRouteImport.update({
  id: '/settlement',
  path: '/settlement',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardServicesRoute = DashboardServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRewardsRoute = DashboardRewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReviewsRoute = DashboardReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRetentionRoute = DashboardRetentionRouteImport.update({
  id: '/retention',
  path: '/retention',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRetailRoute = DashboardRetailRouteImport.update({
  id: '/retail',
  path: '/retail',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReportsRoute = DashboardReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReorderRoute = DashboardReorderRouteImport.update({
  id: '/reorder',
  path: '/reorder',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardQrRoute = DashboardQrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPromosRoute = DashboardPromosRouteImport.update({
  id: '/promos',
  path: '/promos',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPricingRoute = DashboardPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPaymentsRoute = DashboardPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPaymentMethodsRoute = DashboardPaymentMethodsRouteImport.update({
  id: '/payment-methods',
  path: '/payment-methods',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOrdersRoute = DashboardOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMenuRoute = DashboardMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardKnowledgeRoute = DashboardKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInvoicesRoute = DashboardInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInventoryRoute = DashboardInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInboxRoute = DashboardInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardForecastRoute = DashboardForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFloorplanRoute = DashboardFloorplanRouteImport.update({
  id: '/floorplan',
  path: '/floorplan',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEnquiriesRoute = DashboardEnquiriesRouteImport.update({
  id: '/enquiries',
  path: '/enquiries',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDepositsRoute = DashboardDepositsRouteImport.update({
  id: '/deposits',
  path: '/deposits',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCopilotRoute = DashboardCopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardContactsRoute = DashboardContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBookingsRoute = DashboardBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAutomationsRoute = DashboardAutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAccountingRoute = DashboardAccountingRouteImport.update({
  id: '/accounting',
  path: '/accounting',
  getParentRoute: () => DashboardRoute,
} as any)
const BookBusinessIdRoute = BookBusinessIdRouteImport.update({
  id: '/book/$businessId',
  path: '/book/$businessId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMerchantsRoute = AdminMerchantsRouteImport.update({
  id: '/merchants',
  path: '/merchants',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFeaturesRoute = AdminFeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActivityRoute = AdminActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/beneficiaries': typeof BeneficiariesRoute
  '/converter': typeof ConverterRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/enquire': typeof EnquireRoute
  '/get-started': typeof GetStartedRoute
  '/merchant': typeof MerchantRoute
  '/pay': typeof PayRoute
  '/payments': typeof PaymentsRoute
  '/pesaswapApp': typeof PesaswapAppRoute
  '/reports': typeof ReportsRoute
  '/reseller': typeof ResellerRoute
  '/reset-pin': typeof ResetPinRoute
  '/sign-in': typeof SignInRoute
  '/staff-console': typeof StaffConsoleRoute
  '/staff-login': typeof StaffLoginRoute
  '/table': typeof TableRouteWithChildren
  '/admin/activity': typeof AdminActivityRoute
  '/admin/features': typeof AdminFeaturesRoute
  '/admin/merchants': typeof AdminMerchantsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/book/$businessId': typeof BookBusinessIdRoute
  '/dashboard/accounting': typeof DashboardAccountingRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/automations': typeof DashboardAutomationsRoute
  '/dashboard/bookings': typeof DashboardBookingsRoute
  '/dashboard/contacts': typeof DashboardContactsRoute
  '/dashboard/copilot': typeof DashboardCopilotRoute
  '/dashboard/deposits': typeof DashboardDepositsRoute
  '/dashboard/enquiries': typeof DashboardEnquiriesRoute
  '/dashboard/floorplan': typeof DashboardFloorplanRoute
  '/dashboard/forecast': typeof DashboardForecastRoute
  '/dashboard/inbox': typeof DashboardInboxRoute
  '/dashboard/inventory': typeof DashboardInventoryRoute
  '/dashboard/invoices': typeof DashboardInvoicesRoute
  '/dashboard/knowledge': typeof DashboardKnowledgeRoute
  '/dashboard/menu': typeof DashboardMenuRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/payment-methods': typeof DashboardPaymentMethodsRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/pricing': typeof DashboardPricingRoute
  '/dashboard/promos': typeof DashboardPromosRoute
  '/dashboard/qr': typeof DashboardQrRoute
  '/dashboard/reorder': typeof DashboardReorderRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/retail': typeof DashboardRetailRoute
  '/dashboard/retention': typeof DashboardRetentionRoute
  '/dashboard/reviews': typeof DashboardReviewsRoute
  '/dashboard/rewards': typeof DashboardRewardsRoute
  '/dashboard/services': typeof DashboardServicesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/settlement': typeof DashboardSettlementRoute
  '/dashboard/staff': typeof DashboardStaffRoute
  '/dashboard/tables': typeof DashboardTablesRoute
  '/dashboard/telegram': typeof DashboardTelegramRoute
  '/dashboard/whatsapp': typeof DashboardWhatsappRoute
  '/me/$token': typeof MeTokenRoute
  '/q/$code': typeof QCodeRoute
  '/retail/$storeId': typeof RetailStoreIdRoute
  '/table/$tableId': typeof TableTableIdRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/beneficiaries': typeof BeneficiariesRoute
  '/converter': typeof ConverterRoute
  '/enquire': typeof EnquireRoute
  '/get-started': typeof GetStartedRoute
  '/merchant': typeof MerchantRoute
  '/pay': typeof PayRoute
  '/payments': typeof PaymentsRoute
  '/pesaswapApp': typeof PesaswapAppRoute
  '/reports': typeof ReportsRoute
  '/reseller': typeof ResellerRoute
  '/reset-pin': typeof ResetPinRoute
  '/sign-in': typeof SignInRoute
  '/staff-console': typeof StaffConsoleRoute
  '/staff-login': typeof StaffLoginRoute
  '/table': typeof TableRouteWithChildren
  '/admin/activity': typeof AdminActivityRoute
  '/admin/features': typeof AdminFeaturesRoute
  '/admin/merchants': typeof AdminMerchantsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/book/$businessId': typeof BookBusinessIdRoute
  '/dashboard/accounting': typeof DashboardAccountingRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/automations': typeof DashboardAutomationsRoute
  '/dashboard/bookings': typeof DashboardBookingsRoute
  '/dashboard/contacts': typeof DashboardContactsRoute
  '/dashboard/copilot': typeof DashboardCopilotRoute
  '/dashboard/deposits': typeof DashboardDepositsRoute
  '/dashboard/enquiries': typeof DashboardEnquiriesRoute
  '/dashboard/floorplan': typeof DashboardFloorplanRoute
  '/dashboard/forecast': typeof DashboardForecastRoute
  '/dashboard/inbox': typeof DashboardInboxRoute
  '/dashboard/inventory': typeof DashboardInventoryRoute
  '/dashboard/invoices': typeof DashboardInvoicesRoute
  '/dashboard/knowledge': typeof DashboardKnowledgeRoute
  '/dashboard/menu': typeof DashboardMenuRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/payment-methods': typeof DashboardPaymentMethodsRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/pricing': typeof DashboardPricingRoute
  '/dashboard/promos': typeof DashboardPromosRoute
  '/dashboard/qr': typeof DashboardQrRoute
  '/dashboard/reorder': typeof DashboardReorderRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/retail': typeof DashboardRetailRoute
  '/dashboard/retention': typeof DashboardRetentionRoute
  '/dashboard/reviews': typeof DashboardReviewsRoute
  '/dashboard/rewards': typeof DashboardRewardsRoute
  '/dashboard/services': typeof DashboardServicesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/settlement': typeof DashboardSettlementRoute
  '/dashboard/staff': typeof DashboardStaffRoute
  '/dashboard/tables': typeof DashboardTablesRoute
  '/dashboard/telegram': typeof DashboardTelegramRoute
  '/dashboard/whatsapp': typeof DashboardWhatsappRoute
  '/me/$token': typeof MeTokenRoute
  '/q/$code': typeof QCodeRoute
  '/retail/$storeId': typeof RetailStoreIdRoute
  '/table/$tableId': typeof TableTableIdRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/beneficiaries': typeof BeneficiariesRoute
  '/converter': typeof ConverterRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/enquire': typeof EnquireRoute
  '/get-started': typeof GetStartedRoute
  '/merchant': typeof MerchantRoute
  '/pay': typeof PayRoute
  '/payments': typeof PaymentsRoute
  '/pesaswapApp': typeof PesaswapAppRoute
  '/reports': typeof ReportsRoute
  '/reseller': typeof ResellerRoute
  '/reset-pin': typeof ResetPinRoute
  '/sign-in': typeof SignInRoute
  '/staff-console': typeof StaffConsoleRoute
  '/staff-login': typeof StaffLoginRoute
  '/table': typeof TableRouteWithChildren
  '/admin/activity': typeof AdminActivityRoute
  '/admin/features': typeof AdminFeaturesRoute
  '/admin/merchants': typeof AdminMerchantsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/book/$businessId': typeof BookBusinessIdRoute
  '/dashboard/accounting': typeof DashboardAccountingRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/automations': typeof DashboardAutomationsRoute
  '/dashboard/bookings': typeof DashboardBookingsRoute
  '/dashboard/contacts': typeof DashboardContactsRoute
  '/dashboard/copilot': typeof DashboardCopilotRoute
  '/dashboard/deposits': typeof DashboardDepositsRoute
  '/dashboard/enquiries': typeof DashboardEnquiriesRoute
  '/dashboard/floorplan': typeof DashboardFloorplanRoute
  '/dashboard/forecast': typeof DashboardForecastRoute
  '/dashboard/inbox': typeof DashboardInboxRoute
  '/dashboard/inventory': typeof DashboardInventoryRoute
  '/dashboard/invoices': typeof DashboardInvoicesRoute
  '/dashboard/knowledge': typeof DashboardKnowledgeRoute
  '/dashboard/menu': typeof DashboardMenuRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/payment-methods': typeof DashboardPaymentMethodsRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/pricing': typeof DashboardPricingRoute
  '/dashboard/promos': typeof DashboardPromosRoute
  '/dashboard/qr': typeof DashboardQrRoute
  '/dashboard/reorder': typeof DashboardReorderRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/retail': typeof DashboardRetailRoute
  '/dashboard/retention': typeof DashboardRetentionRoute
  '/dashboard/reviews': typeof DashboardReviewsRoute
  '/dashboard/rewards': typeof DashboardRewardsRoute
  '/dashboard/services': typeof DashboardServicesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/settlement': typeof DashboardSettlementRoute
  '/dashboard/staff': typeof DashboardStaffRoute
  '/dashboard/tables': typeof DashboardTablesRoute
  '/dashboard/telegram': typeof DashboardTelegramRoute
  '/dashboard/whatsapp': typeof DashboardWhatsappRoute
  '/me/$token': typeof MeTokenRoute
  '/q/$code': typeof QCodeRoute
  '/retail/$storeId': typeof RetailStoreIdRoute
  '/table/$tableId': typeof TableTableIdRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/beneficiaries'
    | '/converter'
    | '/dashboard'
    | '/enquire'
    | '/get-started'
    | '/merchant'
    | '/pay'
    | '/payments'
    | '/pesaswapApp'
    | '/reports'
    | '/reseller'
    | '/reset-pin'
    | '/sign-in'
    | '/staff-console'
    | '/staff-login'
    | '/table'
    | '/admin/activity'
    | '/admin/features'
    | '/admin/merchants'
    | '/admin/settings'
    | '/book/$businessId'
    | '/dashboard/accounting'
    | '/dashboard/analytics'
    | '/dashboard/automations'
    | '/dashboard/bookings'
    | '/dashboard/contacts'
    | '/dashboard/copilot'
    | '/dashboard/deposits'
    | '/dashboard/enquiries'
    | '/dashboard/floorplan'
    | '/dashboard/forecast'
    | '/dashboard/inbox'
    | '/dashboard/inventory'
    | '/dashboard/invoices'
    | '/dashboard/knowledge'
    | '/dashboard/menu'
    | '/dashboard/orders'
    | '/dashboard/payment-methods'
    | '/dashboard/payments'
    | '/dashboard/pricing'
    | '/dashboard/promos'
    | '/dashboard/qr'
    | '/dashboard/reorder'
    | '/dashboard/reports'
    | '/dashboard/retail'
    | '/dashboard/retention'
    | '/dashboard/reviews'
    | '/dashboard/rewards'
    | '/dashboard/services'
    | '/dashboard/settings'
    | '/dashboard/settlement'
    | '/dashboard/staff'
    | '/dashboard/tables'
    | '/dashboard/telegram'
    | '/dashboard/whatsapp'
    | '/me/$token'
    | '/q/$code'
    | '/retail/$storeId'
    | '/table/$tableId'
    | '/admin/'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/beneficiaries'
    | '/converter'
    | '/enquire'
    | '/get-started'
    | '/merchant'
    | '/pay'
    | '/payments'
    | '/pesaswapApp'
    | '/reports'
    | '/reseller'
    | '/reset-pin'
    | '/sign-in'
    | '/staff-console'
    | '/staff-login'
    | '/table'
    | '/admin/activity'
    | '/admin/features'
    | '/admin/merchants'
    | '/admin/settings'
    | '/book/$businessId'
    | '/dashboard/accounting'
    | '/dashboard/analytics'
    | '/dashboard/automations'
    | '/dashboard/bookings'
    | '/dashboard/contacts'
    | '/dashboard/copilot'
    | '/dashboard/deposits'
    | '/dashboard/enquiries'
    | '/dashboard/floorplan'
    | '/dashboard/forecast'
    | '/dashboard/inbox'
    | '/dashboard/inventory'
    | '/dashboard/invoices'
    | '/dashboard/knowledge'
    | '/dashboard/menu'
    | '/dashboard/orders'
    | '/dashboard/payment-methods'
    | '/dashboard/payments'
    | '/dashboard/pricing'
    | '/dashboard/promos'
    | '/dashboard/qr'
    | '/dashboard/reorder'
    | '/dashboard/reports'
    | '/dashboard/retail'
    | '/dashboard/retention'
    | '/dashboard/reviews'
    | '/dashboard/rewards'
    | '/dashboard/services'
    | '/dashboard/settings'
    | '/dashboard/settlement'
    | '/dashboard/staff'
    | '/dashboard/tables'
    | '/dashboard/telegram'
    | '/dashboard/whatsapp'
    | '/me/$token'
    | '/q/$code'
    | '/retail/$storeId'
    | '/table/$tableId'
    | '/admin'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/beneficiaries'
    | '/converter'
    | '/dashboard'
    | '/enquire'
    | '/get-started'
    | '/merchant'
    | '/pay'
    | '/payments'
    | '/pesaswapApp'
    | '/reports'
    | '/reseller'
    | '/reset-pin'
    | '/sign-in'
    | '/staff-console'
    | '/staff-login'
    | '/table'
    | '/admin/activity'
    | '/admin/features'
    | '/admin/merchants'
    | '/admin/settings'
    | '/book/$businessId'
    | '/dashboard/accounting'
    | '/dashboard/analytics'
    | '/dashboard/automations'
    | '/dashboard/bookings'
    | '/dashboard/contacts'
    | '/dashboard/copilot'
    | '/dashboard/deposits'
    | '/dashboard/enquiries'
    | '/dashboard/floorplan'
    | '/dashboard/forecast'
    | '/dashboard/inbox'
    | '/dashboard/inventory'
    | '/dashboard/invoices'
    | '/dashboard/knowledge'
    | '/dashboard/menu'
    | '/dashboard/orders'
    | '/dashboard/payment-methods'
    | '/dashboard/payments'
    | '/dashboard/pricing'
    | '/dashboard/promos'
    | '/dashboard/qr'
    | '/dashboard/reorder'
    | '/dashboard/reports'
    | '/dashboard/retail'
    | '/dashboard/retention'
    | '/dashboard/reviews'
    | '/dashboard/rewards'
    | '/dashboard/services'
    | '/dashboard/settings'
    | '/dashboard/settlement'
    | '/dashboard/staff'
    | '/dashboard/tables'
    | '/dashboard/telegram'
    | '/dashboard/whatsapp'
    | '/me/$token'
    | '/q/$code'
    | '/retail/$storeId'
    | '/table/$tableId'
    | '/admin/'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BeneficiariesRoute: typeof BeneficiariesRoute
  ConverterRoute: typeof ConverterRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  EnquireRoute: typeof EnquireRoute
  GetStartedRoute: typeof GetStartedRoute
  MerchantRoute: typeof MerchantRoute
  PayRoute: typeof PayRoute
  PaymentsRoute: typeof PaymentsRoute
  PesaswapAppRoute: typeof PesaswapAppRoute
  ReportsRoute: typeof ReportsRoute
  ResellerRoute: typeof ResellerRoute
  ResetPinRoute: typeof ResetPinRoute
  SignInRoute: typeof SignInRoute
  StaffConsoleRoute: typeof StaffConsoleRoute
  StaffLoginRoute: typeof StaffLoginRoute
  TableRoute: typeof TableRouteWithChildren
  BookBusinessIdRoute: typeof BookBusinessIdRoute
  MeTokenRoute: typeof MeTokenRoute
  QCodeRoute: typeof QCodeRoute
  RetailStoreIdRoute: typeof RetailStoreIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/table': {
      id: '/table'
      path: '/table'
      fullPath: '/table'
      preLoaderRoute: typeof TableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff-login': {
      id: '/staff-login'
      path: '/staff-login'
      fullPath: '/staff-login'
      preLoaderRoute: typeof StaffLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff-console': {
      id: '/staff-console'
      path: '/staff-console'
      fullPath: '/staff-console'
      preLoaderRoute: typeof StaffConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-pin': {
      id: '/reset-pin'
      path: '/reset-pin'
      fullPath: '/reset-pin'
      preLoaderRoute: typeof ResetPinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reseller': {
      id: '/reseller'
      path: '/reseller'
      fullPath: '/reseller'
      preLoaderRoute: typeof ResellerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pesaswapApp': {
      id: '/pesaswapApp'
      path: '/pesaswapApp'
      fullPath: '/pesaswapApp'
      preLoaderRoute: typeof PesaswapAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay': {
      id: '/pay'
      path: '/pay'
      fullPath: '/pay'
      preLoaderRoute: typeof PayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant': {
      id: '/merchant'
      path: '/merchant'
      fullPath: '/merchant'
      preLoaderRoute: typeof MerchantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-started': {
      id: '/get-started'
      path: '/get-started'
      fullPath: '/get-started'
      preLoaderRoute: typeof GetStartedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enquire': {
      id: '/enquire'
      path: '/enquire'
      fullPath: '/enquire'
      preLoaderRoute: typeof EnquireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/converter': {
      id: '/converter'
      path: '/converter'
      fullPath: '/converter'
      preLoaderRoute: typeof ConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beneficiaries': {
      id: '/beneficiaries'
      path: '/beneficiaries'
      fullPath: '/beneficiaries'
      preLoaderRoute: typeof BeneficiariesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/table/$tableId': {
      id: '/table/$tableId'
      path: '/$tableId'
      fullPath: '/table/$tableId'
      preLoaderRoute: typeof TableTableIdRouteImport
      parentRoute: typeof TableRoute
    }
    '/retail/$storeId': {
      id: '/retail/$storeId'
      path: '/retail/$storeId'
      fullPath: '/retail/$storeId'
      preLoaderRoute: typeof RetailStoreIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/q/$code': {
      id: '/q/$code'
      path: '/q/$code'
      fullPath: '/q/$code'
      preLoaderRoute: typeof QCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/$token': {
      id: '/me/$token'
      path: '/me/$token'
      fullPath: '/me/$token'
      preLoaderRoute: typeof MeTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/whatsapp': {
      id: '/dashboard/whatsapp'
      path: '/whatsapp'
      fullPath: '/dashboard/whatsapp'
      preLoaderRoute: typeof DashboardWhatsappRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/telegram': {
      id: '/dashboard/telegram'
      path: '/telegram'
      fullPath: '/dashboard/telegram'
      preLoaderRoute: typeof DashboardTelegramRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tables': {
      id: '/dashboard/tables'
      path: '/tables'
      fullPath: '/dashboard/tables'
      preLoaderRoute: typeof DashboardTablesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/staff': {
      id: '/dashboard/staff'
      path: '/staff'
      fullPath: '/dashboard/staff'
      preLoaderRoute: typeof DashboardStaffRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settlement': {
      id: '/dashboard/settlement'
      path: '/settlement'
      fullPath: '/dashboard/settlement'
      preLoaderRoute: typeof DashboardSettlementRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/services': {
      id: '/dashboard/services'
      path: '/services'
      fullPath: '/dashboard/services'
      preLoaderRoute: typeof DashboardServicesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/rewards': {
      id: '/dashboard/rewards'
      path: '/rewards'
      fullPath: '/dashboard/rewards'
      preLoaderRoute: typeof DashboardRewardsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reviews': {
      id: '/dashboard/reviews'
      path: '/reviews'
      fullPath: '/dashboard/reviews'
      preLoaderRoute: typeof DashboardReviewsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/retention': {
      id: '/dashboard/retention'
      path: '/retention'
      fullPath: '/dashboard/retention'
      preLoaderRoute: typeof DashboardRetentionRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/retail': {
      id: '/dashboard/retail'
      path: '/retail'
      fullPath: '/dashboard/retail'
      preLoaderRoute: typeof DashboardRetailRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reports': {
      id: '/dashboard/reports'
      path: '/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof DashboardReportsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reorder': {
      id: '/dashboard/reorder'
      path: '/reorder'
      fullPath: '/dashboard/reorder'
      preLoaderRoute: typeof DashboardReorderRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/qr': {
      id: '/dashboard/qr'
      path: '/qr'
      fullPath: '/dashboard/qr'
      preLoaderRoute: typeof DashboardQrRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/promos': {
      id: '/dashboard/promos'
      path: '/promos'
      fullPath: '/dashboard/promos'
      preLoaderRoute: typeof DashboardPromosRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/pricing': {
      id: '/dashboard/pricing'
      path: '/pricing'
      fullPath: '/dashboard/pricing'
      preLoaderRoute: typeof DashboardPricingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/payments': {
      id: '/dashboard/payments'
      path: '/payments'
      fullPath: '/dashboard/payments'
      preLoaderRoute: typeof DashboardPaymentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/payment-methods': {
      id: '/dashboard/payment-methods'
      path: '/payment-methods'
      fullPath: '/dashboard/payment-methods'
      preLoaderRoute: typeof DashboardPaymentMethodsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/orders': {
      id: '/dashboard/orders'
      path: '/orders'
      fullPath: '/dashboard/orders'
      preLoaderRoute: typeof DashboardOrdersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/menu': {
      id: '/dashboard/menu'
      path: '/menu'
      fullPath: '/dashboard/menu'
      preLoaderRoute: typeof DashboardMenuRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/knowledge': {
      id: '/dashboard/knowledge'
      path: '/knowledge'
      fullPath: '/dashboard/knowledge'
      preLoaderRoute: typeof DashboardKnowledgeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/invoices': {
      id: '/dashboard/invoices'
      path: '/invoices'
      fullPath: '/dashboard/invoices'
      preLoaderRoute: typeof DashboardInvoicesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/inventory': {
      id: '/dashboard/inventory'
      path: '/inventory'
      fullPath: '/dashboard/inventory'
      preLoaderRoute: typeof DashboardInventoryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/inbox': {
      id: '/dashboard/inbox'
      path: '/inbox'
      fullPath: '/dashboard/inbox'
      preLoaderRoute: typeof DashboardInboxRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/forecast': {
      id: '/dashboard/forecast'
      path: '/forecast'
      fullPath: '/dashboard/forecast'
      preLoaderRoute: typeof DashboardForecastRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/floorplan': {
      id: '/dashboard/floorplan'
      path: '/floorplan'
      fullPath: '/dashboard/floorplan'
      preLoaderRoute: typeof DashboardFloorplanRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/enquiries': {
      id: '/dashboard/enquiries'
      path: '/enquiries'
      fullPath: '/dashboard/enquiries'
      preLoaderRoute: typeof DashboardEnquiriesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/deposits': {
      id: '/dashboard/deposits'
      path: '/deposits'
      fullPath: '/dashboard/deposits'
      preLoaderRoute: typeof DashboardDepositsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/copilot': {
      id: '/dashboard/copilot'
      path: '/copilot'
      fullPath: '/dashboard/copilot'
      preLoaderRoute: typeof DashboardCopilotRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/contacts': {
      id: '/dashboard/contacts'
      path: '/contacts'
      fullPath: '/dashboard/contacts'
      preLoaderRoute: typeof DashboardContactsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/bookings': {
      id: '/dashboard/bookings'
      path: '/bookings'
      fullPath: '/dashboard/bookings'
      preLoaderRoute: typeof DashboardBookingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/automations': {
      id: '/dashboard/automations'
      path: '/automations'
      fullPath: '/dashboard/automations'
      preLoaderRoute: typeof DashboardAutomationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/accounting': {
      id: '/dashboard/accounting'
      path: '/accounting'
      fullPath: '/dashboard/accounting'
      preLoaderRoute: typeof DashboardAccountingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/book/$businessId': {
      id: '/book/$businessId'
      path: '/book/$businessId'
      fullPath: '/book/$businessId'
      preLoaderRoute: typeof BookBusinessIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/merchants': {
      id: '/admin/merchants'
      path: '/merchants'
      fullPath: '/admin/merchants'
      preLoaderRoute: typeof AdminMerchantsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/features': {
      id: '/admin/features'
      path: '/features'
      fullPath: '/admin/features'
      preLoaderRoute: typeof AdminFeaturesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/activity': {
      id: '/admin/activity'
      path: '/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AdminActivityRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminActivityRoute: typeof AdminActivityRoute
  AdminFeaturesRoute: typeof AdminFeaturesRoute
  AdminMerchantsRoute: typeof AdminMerchantsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminActivityRoute: AdminActivityRoute,
  AdminFeaturesRoute: AdminFeaturesRoute,
  AdminMerchantsRoute: AdminMerchantsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DashboardRouteChildren {
  DashboardAccountingRoute: typeof DashboardAccountingRoute
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardAutomationsRoute: typeof DashboardAutomationsRoute
  DashboardBookingsRoute: typeof DashboardBookingsRoute
  DashboardContactsRoute: typeof DashboardContactsRoute
  DashboardCopilotRoute: typeof DashboardCopilotRoute
  DashboardDepositsRoute: typeof DashboardDepositsRoute
  DashboardEnquiriesRoute: typeof DashboardEnquiriesRoute
  DashboardFloorplanRoute: typeof DashboardFloorplanRoute
  DashboardForecastRoute: typeof DashboardForecastRoute
  DashboardInboxRoute: typeof DashboardInboxRoute
  DashboardInventoryRoute: typeof DashboardInventoryRoute
  DashboardInvoicesRoute: typeof DashboardInvoicesRoute
  DashboardKnowledgeRoute: typeof DashboardKnowledgeRoute
  DashboardMenuRoute: typeof DashboardMenuRoute
  DashboardOrdersRoute: typeof DashboardOrdersRoute
  DashboardPaymentMethodsRoute: typeof DashboardPaymentMethodsRoute
  DashboardPaymentsRoute: typeof DashboardPaymentsRoute
  DashboardPricingRoute: typeof DashboardPricingRoute
  DashboardPromosRoute: typeof DashboardPromosRoute
  DashboardQrRoute: typeof DashboardQrRoute
  DashboardReorderRoute: typeof DashboardReorderRoute
  DashboardReportsRoute: typeof DashboardReportsRoute
  DashboardRetailRoute: typeof DashboardRetailRoute
  DashboardRetentionRoute: typeof DashboardRetentionRoute
  DashboardReviewsRoute: typeof DashboardReviewsRoute
  DashboardRewardsRoute: typeof DashboardRewardsRoute
  DashboardServicesRoute: typeof DashboardServicesRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardSettlementRoute: typeof DashboardSettlementRoute
  DashboardStaffRoute: typeof DashboardStaffRoute
  DashboardTablesRoute: typeof DashboardTablesRoute
  DashboardTelegramRoute: typeof DashboardTelegramRoute
  DashboardWhatsappRoute: typeof DashboardWhatsappRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAccountingRoute: DashboardAccountingRoute,
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardAutomationsRoute: DashboardAutomationsRoute,
  DashboardBookingsRoute: DashboardBookingsRoute,
  DashboardContactsRoute: DashboardContactsRoute,
  DashboardCopilotRoute: DashboardCopilotRoute,
  DashboardDepositsRoute: DashboardDepositsRoute,
  DashboardEnquiriesRoute: DashboardEnquiriesRoute,
  DashboardFloorplanRoute: DashboardFloorplanRoute,
  DashboardForecastRoute: DashboardForecastRoute,
  DashboardInboxRoute: DashboardInboxRoute,
  DashboardInventoryRoute: DashboardInventoryRoute,
  DashboardInvoicesRoute: DashboardInvoicesRoute,
  DashboardKnowledgeRoute: DashboardKnowledgeRoute,
  DashboardMenuRoute: DashboardMenuRoute,
  DashboardOrdersRoute: DashboardOrdersRoute,
  DashboardPaymentMethodsRoute: DashboardPaymentMethodsRoute,
  DashboardPaymentsRoute: DashboardPaymentsRoute,
  DashboardPricingRoute: DashboardPricingRoute,
  DashboardPromosRoute: DashboardPromosRoute,
  DashboardQrRoute: DashboardQrRoute,
  DashboardReorderRoute: DashboardReorderRoute,
  DashboardReportsRoute: DashboardReportsRoute,
  DashboardRetailRoute: DashboardRetailRoute,
  DashboardRetentionRoute: DashboardRetentionRoute,
  DashboardReviewsRoute: DashboardReviewsRoute,
  DashboardRewardsRoute: DashboardRewardsRoute,
  DashboardServicesRoute: DashboardServicesRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSettlementRoute: DashboardSettlementRoute,
  DashboardStaffRoute: DashboardStaffRoute,
  DashboardTablesRoute: DashboardTablesRoute,
  DashboardTelegramRoute: DashboardTelegramRoute,
  DashboardWhatsappRoute: DashboardWhatsappRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface TableRouteChildren {
  TableTableIdRoute: typeof TableTableIdRoute
}

const TableRouteChildren: TableRouteChildren = {
  TableTableIdRoute: TableTableIdRoute,
}

const TableRouteWithChildren = TableRoute._addFileChildren(TableRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BeneficiariesRoute: BeneficiariesRoute,
  ConverterRoute: ConverterRoute,
  DashboardRoute: DashboardRouteWithChildren,
  EnquireRoute: EnquireRoute,
  GetStartedRoute: GetStartedRoute,
  MerchantRoute: MerchantRoute,
  PayRoute: PayRoute,
  PaymentsRoute: PaymentsRoute,
  PesaswapAppRoute: PesaswapAppRoute,
  ReportsRoute: ReportsRoute,
  ResellerRoute: ResellerRoute,
  ResetPinRoute: ResetPinRoute,
  SignInRoute: SignInRoute,
  StaffConsoleRoute: StaffConsoleRoute,
  StaffLoginRoute: StaffLoginRoute,
  TableRoute: TableRouteWithChildren,
  BookBusinessIdRoute: BookBusinessIdRoute,
  MeTokenRoute: MeTokenRoute,
  QCodeRoute: QCodeRoute,
  RetailStoreIdRoute: RetailStoreIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
